config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:new, :create, :index, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user if user.try(:is_password?, password)
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  validates :password_digest, :session_token, :username, presence: true
  validates :session_token, :username, uniqueness: true
  validates :password, length: { minimum: 8, allow_nil: true }

  after_initialize :ensure_session_token

  attr_reader :password

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save
    session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def login!(user)
    session[:session_token] = user.reset_session_token!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      login!(user)
      flash[:success] = "Welcome!"
      redirect_to user_url(user)
    else
      flash[:failure] = user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username
    <input type="text" name="user[username]">
  </label>
  <label>Password
    <input type="password" name="user[password]">
  </label>
  
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>Show</h1>